In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.00822591 -1.60490214  0.43881486  0.18544308  0.57458819]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.00822591 -1.60490214  0.43881486  0.18544308  0.57458819]


In [5]:
print(np.dot(a, a.T))

4.149329561646616


In [6]:
a = np.random.randn(5,1)
print(a)

[[ 1.1365594 ]
 [-1.37194889]
 [-0.72952783]
 [-0.24542371]
 [-0.2857313 ]]


In [7]:
print(a.T)

[[ 1.1365594  -1.37194889 -0.72952783 -0.24542371 -0.2857313 ]]


In [8]:
print(np.dot(a,a.T))

[[ 1.29176727 -1.55930141 -0.82915171 -0.27893863 -0.32475059]
 [-1.55930141  1.88224375  1.00087489  0.33670879  0.39200874]
 [-0.82915171  1.00087489  0.53221085  0.17904343  0.20844893]
 [-0.27893863  0.33670879  0.17904343  0.0602328   0.07012524]
 [-0.32475059  0.39200874  0.20844893  0.07012524  0.08164238]]


- a = np.random.randn(5) : Don't use
    - a.shape=(5, ) : rank 1 array
- a = np.random.randn(5,1) : Column Vector
    - a.shape=(5, 1)
- a = np.random.randn(1,5) : row Vector
    - a.shape=(1, 5)